AllCops:
    RunRailsCops: true

# Style/IndentationWidth:
    # Number of spaces for each indentation level.
    # Width: 4

Metrics/LineLength:
    Max: 120
    AllowURI: true
Style/WhileUntilModifier:
    MaxLineLength: 120
Style/IfUnlessModifier:
    MaxLineLength: 120
