branch-defaults:
  master:
    environment: shpt-production
global:
  application_name: SHPT-production
  default_ec2_keyname: SHPT_apse1
  default_platform: Ruby 2.2 (Puma)
  default_region: ap-southeast-1
  profile: null
  sc: git
